import type { Inspection, ProductAnalysis, PackageCheck, FixSuggestion } from '@/types';

export const mockInspections: Inspection[] = [
  {
    id: 'INSP-2026-0042',
    product: 'ABC Premium Biscuits',
    category: 'Packaged Food',
    netQuantity: '500 g',
    mrp: '₹120',
    manufacturer: 'ABC Foods Pvt. Ltd.',
    countryOfOrigin: 'India',
    consumerCare: '1800-XXX-XXXX',
    score: 94,
    status: 'potential',
    date: '2026-09-07',
    time: '10:42 AM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0041',
    product: 'FreshGrow Organic Juice',
    category: 'Beverages',
    netQuantity: '1 L',
    mrp: '₹95',
    manufacturer: 'FreshGrow Beverages',
    countryOfOrigin: 'India',
    consumerCare: '1800-555-1234',
    score: 100,
    status: 'compliant',
    date: '2026-09-07',
    time: '09:15 AM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0040',
    product: 'Mountain Spring Water',
    category: 'Bottled Water',
    netQuantity: '750 ml',
    mrp: '₹40',
    manufacturer: 'Himalayan Aqua Ltd.',
    countryOfOrigin: 'India',
    consumerCare: '1800-444-5678',
    score: 87,
    status: 'potential',
    date: '2026-09-06',
    time: '04:30 PM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0039',
    product: 'Golden Harvest Rice',
    category: 'Packaged Food',
    netQuantity: '5 kg',
    mrp: '₹450',
    manufacturer: 'Golden Harvest Mills',
    countryOfOrigin: 'India',
    consumerCare: '1800-333-9012',
    score: 100,
    status: 'compliant',
    date: '2026-09-06',
    time: '11:20 AM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0038',
    product: 'PureLite Cooking Oil',
    category: 'Packaged Food',
    netQuantity: '1 L',
    mrp: '₹185',
    manufacturer: 'PureLite Foods Inc.',
    countryOfOrigin: 'India',
    consumerCare: '1800-222-3456',
    score: 72,
    status: 'pending',
    date: '2026-09-05',
    time: '02:10 PM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0037',
    product: 'ChocoDelight Chocolate Bar',
    category: 'Confectionery',
    netQuantity: '100 g',
    mrp: '₹50',
    manufacturer: 'ChocoDelight Confections',
    countryOfOrigin: 'India',
    consumerCare: '1800-111-7890',
    score: 100,
    status: 'compliant',
    date: '2026-09-05',
    time: '09:45 AM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0036',
    product: 'NatureFresh Tea Leaves',
    category: 'Packaged Food',
    netQuantity: '250 g',
    mrp: '₹160',
    manufacturer: 'NatureFresh Beverages',
    countryOfOrigin: 'India',
    consumerCare: '1800-999-4567',
    score: 81,
    status: 'potential',
    date: '2026-09-04',
    time: '03:25 PM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0035',
    product: 'SparkleDetergent Powder',
    category: 'Household',
    netQuantity: '2 kg',
    mrp: '₹220',
    manufacturer: 'Sparkle Home Care',
    countryOfOrigin: 'India',
    consumerCare: '1800-888-2345',
    score: 100,
    status: 'compliant',
    date: '2026-09-04',
    time: '10:10 AM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0034',
    product: 'HealthPlus Multivitamin',
    category: 'Dietary Supplement',
    netQuantity: '30 tablets',
    mrp: '₹350',
    manufacturer: 'HealthPlus Pharma',
    countryOfOrigin: 'India',
    consumerCare: '1800-777-6789',
    score: 65,
    status: 'pending',
    date: '2026-09-03',
    time: '01:50 PM',
    inspector: 'AI Engine v2.1',
  },
  {
    id: 'INSP-2026-0033',
    product: 'AromaRoast Coffee Beans',
    category: 'Beverages',
    netQuantity: '200 g',
    mrp: '₹280',
    manufacturer: 'AromaRoast Coffee Co.',
    countryOfOrigin: 'India',
    consumerCare: '1800-666-1122',
    score: 100,
    status: 'compliant',
    date: '2026-09-03',
    time: '08:30 AM',
    inspector: 'AI Engine v2.1',
  },
];

export const demoAnalysis: ProductAnalysis = {
  product: 'ABC Premium Biscuits',
  category: 'Packaged Food',
  netQuantity: '500 g',
  mrp: '₹120',
  manufacturer: 'ABC Foods Pvt. Ltd.',
  countryOfOrigin: 'India',
  consumerCare: '1800-XXX-XXXX',
  score: 94,
  status: 'Potentially Compliant — Human Verification Recommended',
  detectedFields: [
    { label: 'Product Name', value: 'ABC Premium Biscuits', confidence: 99, compliant: true },
    { label: 'Category', value: 'Packaged Food', confidence: 97, compliant: true },
    { label: 'Net Quantity', value: '500 g', confidence: 98, compliant: true, note: 'Declared in standard units (grams)' },
    { label: 'MRP', value: '₹120', confidence: 96, compliant: true, note: 'Clearly visible, includes ₹ symbol' },
    { label: 'Manufacturer Name', value: 'ABC Foods Pvt. Ltd.', confidence: 95, compliant: true },
    { label: 'Country of Origin', value: 'India', confidence: 93, compliant: true },
    { label: 'Consumer Care Contact', value: '1800-XXX-XXXX', confidence: 88, compliant: true, note: 'Toll-free number detected' },
    { label: 'Batch / Lot Number', value: 'BN-2026-08-15', confidence: 82, compliant: true },
    { label: 'Date of Manufacture', value: '15/08/2026', confidence: 90, compliant: true },
    { label: 'Best Before', value: '6 months from manufacture', confidence: 85, compliant: true },
    { label: 'FSSAI License No.', value: 'FSSAI-100180XX00000', confidence: 79, compliant: false, note: 'Format appears valid but requires manual verification against FSSAI database' },
    { label: 'Nutritional Information', value: 'Per 100g: Energy 452 kcal, Protein 7g, Fat 18g, Carbs 68g', confidence: 91, compliant: true, note: 'Per-100g declaration present as required' },
    { label: 'Vegetarian/Non-Veg Symbol', value: 'Green dot (Vegetarian)', confidence: 94, compliant: true },
    { label: 'Ingredients List', value: 'Wheat flour, sugar, edible vegetable oil, ...', confidence: 92, compliant: true },
    { label: 'Allergen Declaration', value: 'Contains wheat and milk. May contain traces of nuts.', confidence: 87, compliant: true },
  ],
};

export const mockPackageChecks: PackageCheck[] = [
  {
    id: 'PKG-2026-0156',
    product: 'ABC Premium Biscuits',
    category: 'Packaged Food',
    netQuantity: '500 g',
    mrp: '₹120',
    score: 94,
    status: 'potential',
    date: '2026-09-07',
    time: '11:30 AM',
    issues: 1,
  },
  {
    id: 'PKG-2026-0155',
    product: 'FreshGrow Organic Juice',
    category: 'Beverages',
    netQuantity: '1 L',
    mrp: '₹95',
    score: 100,
    status: 'compliant',
    date: '2026-09-07',
    time: '09:45 AM',
    issues: 0,
  },
  {
    id: 'PKG-2026-0154',
    product: 'Golden Harvest Rice',
    category: 'Packaged Food',
    netQuantity: '5 kg',
    mrp: '₹450',
    score: 100,
    status: 'compliant',
    date: '2026-09-06',
    time: '03:20 PM',
    issues: 0,
  },
  {
    id: 'PKG-2026-0153',
    product: 'PureLite Cooking Oil',
    category: 'Packaged Food',
    netQuantity: '1 L',
    mrp: '₹185',
    score: 72,
    status: 'pending',
    date: '2026-09-06',
    time: '10:15 AM',
    issues: 3,
  },
  {
    id: 'PKG-2026-0152',
    product: 'NatureFresh Tea Leaves',
    category: 'Packaged Food',
    netQuantity: '250 g',
    mrp: '₹160',
    score: 81,
    status: 'potential',
    date: '2026-09-05',
    time: '02:30 PM',
    issues: 2,
  },
  {
    id: 'PKG-2026-0151',
    product: 'ChocoDelight Chocolate Bar',
    category: 'Confectionery',
    netQuantity: '100 g',
    mrp: '₹50',
    score: 100,
    status: 'compliant',
    date: '2026-09-05',
    time: '08:50 AM',
    issues: 0,
  },
];

export const demoPackageAnalysis: ProductAnalysis = {
  product: 'ABC Premium Biscuits',
  category: 'Packaged Food',
  netQuantity: '500 g',
  mrp: '₹120',
  manufacturer: 'ABC Foods Pvt. Ltd.',
  countryOfOrigin: 'India',
  consumerCare: '1800-XXX-XXXX',
  score: 94,
  status: 'Potential Issue — Human Verification Recommended',
  detectedFields: [
    { label: 'Product Name', value: 'ABC Premium Biscuits', confidence: 99, compliant: true },
    { label: 'Category', value: 'Packaged Food', confidence: 97, compliant: true },
    { label: 'Net Quantity', value: '500 g', confidence: 98, compliant: true, note: 'Declared in standard units (grams)' },
    { label: 'MRP', value: '₹120', confidence: 96, compliant: true, note: 'Clearly visible, includes ₹ symbol' },
    { label: 'Manufacturer Name', value: 'ABC Foods Pvt. Ltd.', confidence: 95, compliant: true },
    { label: 'Country of Origin', value: 'India', confidence: 93, compliant: true },
    { label: 'Consumer Care Contact', value: '1800-XXX-XXXX', confidence: 88, compliant: true, note: 'Toll-free number detected' },
    { label: 'Batch / Lot Number', value: 'BN-2026-08-15', confidence: 82, compliant: true },
    { label: 'Date of Manufacture', value: '15/08/2026', confidence: 90, compliant: true },
    { label: 'Best Before', value: '6 months from manufacture', confidence: 85, compliant: true },
    { label: 'FSSAI License No.', value: 'FSSAI-100180XX00000', confidence: 79, compliant: false, note: 'Format appears valid but requires manual verification against FSSAI database' },
    { label: 'Nutritional Information', value: 'Per 100g: Energy 452 kcal, Protein 7g, Fat 18g, Carbs 68g', confidence: 91, compliant: true, note: 'Per-100g declaration present as required' },
    { label: 'Vegetarian/Non-Veg Symbol', value: 'Green dot (Vegetarian)', confidence: 94, compliant: true },
    { label: 'Ingredients List', value: 'Wheat flour, sugar, edible vegetable oil, ...', confidence: 92, compliant: true },
    { label: 'Allergen Declaration', value: 'Contains wheat and milk. May contain traces of nuts.', confidence: 87, compliant: true },
  ],
};

export const demoFixSuggestions: FixSuggestion[] = [
  {
    field: 'FSSAI License No.',
    detected: 'FSSAI-100180XX00000',
    reason: 'The FSSAI license number was detected at 79% confidence. While the format appears valid, the placeholder "XX" suggests this may be a draft or template number. It must be cross-checked against the FSSAI central registry to confirm the license is active and linked to ABC Foods Pvt. Ltd.',
    action: 'Replace the placeholder digits with the actual 14-digit FSSAI license number and verify it on the FSSAI online portal (foscos.fssai.gov.in) before printing.',
    severity: 'medium',
  },
];

